# Generated by Django 2.2.3 on 2019-07-16 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('aliases', models.ManyToManyField(related_name='_machine_aliases_+', to='craftapp.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('makes', models.IntegerField(default=1)),
                ('has_byproducts', models.BooleanField(default=False)),
                ('is_shapeless', models.BooleanField(default=False)),
                ('machine_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftapp.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Slotdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
                ('item', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftapp.Recipe')),
            ],
        ),
    ]
