# Generated by Django 2.2.3 on 2019-07-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftapp', '0002_byproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='max_stack',
            field=models.IntegerField(default=64),
        ),
    ]
