# Generated by Django 2.2.3 on 2019-07-20 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craftapp', '0005_auto_20190719_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mod',
            old_name='mod_id',
            new_name='name',
        ),
    ]
