# Generated by Django 2.2.3 on 2019-07-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftapp', '0007_auto_20190721_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='item',
            name='item_id',
            field=models.CharField(default='', max_length=300, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
